namespace = SDMIv1

; ---- Detect when Character Menu is opened

[ShaderOverridePS_Char_Menu]
hash = 97dc719f31172659
if $enable_mods
    $in_char_menu = 1
endif

; ---- BODY

[ShaderOverrideVS_ALL_CHARACTER_Full_Body]
hash = 165e9f9487316c46
if $enable_mods
	checktextureoverride = ib
endif

; ---- TEXTURES

[ShaderOverrideVS_ALL_CHARACTER_Body]
hash = c2e09f40964eecbb
if $enable_mods
	checktextureoverride = ib
endif

[ShaderOverrideVS_ALL_CHARACTER_Legs]
hash = eddbb8fbe27a112e
if $enable_mods
	checktextureoverride = ib
endif

[ShaderOverrideBodyVS_ALL_CHARACTER_Hair]
hash = c54ed8422bb01cae
if $enable_mods
	checktextureoverride = ib
endif

[ShaderOverrideVS_ALL_CHARACTER_Skin] 
hash = 531516fd7eaec7ed
if $enable_mods
	checktextureoverride = ib
endif

[ShaderOverrideVS_ALL_CHARACTER_Fringe]
hash = 6df39b79d2b50255
if $enable_mods
	checktextureoverride = ib
endif

; [ShaderOverrideVS_ALL_CHARACTER_Face]
; hash = 2ab20e5eccfbe98b
; if $enable_mods
; 	checktextureoverride = ib
; endif

; [ShaderOverrideVS_ALL_CHARACTER_Eyes]
; hash = 0f30ef8f6b2952a7
; if $enable_mods
; 	checktextureoverride = ib
; endif

; [ShaderOverrideVS_ALL_CHARACTER_Neck]
; hash = cc689c046ac3f4a7
; if $enable_mods
; 	checktextureoverride = ib
; endif

; ---- CHARACHER OUTLINES

[ShaderOverrideVS_ALL_CHARACTER_Neck_Outline]
hash = 9c2276d9ccd270e6
if $enable_mods
	checktextureoverride = ib
endif

[ShaderOverrideVS_ALL_CHARACTER_Body_Outline]
hash = 0329a3e48e344808
if $enable_mods
	checktextureoverride = ib
endif

[ShaderOverrideBodyVS_ALL_CHARACTER_Skin_Hair_Outline]
hash = 822edc37da0ccb14
if $enable_mods
	checktextureoverride = ib
endif
